# Docs for the Azure Web Apps Deploy action: https://github.com/azure/functions-action
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure Functions: https://aka.ms/python-webapps-actions

name: Build and Deploy Python Azure Function App - feedback-system-func

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: './backend' # Set this to the path to your Azure Function project
  PYTHON_VERSION: '3.10' # Set this to the Python version to use (supports 3.6, 3.7, 3.8, 3.10)

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and Package Azure Function
    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set up Python version
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      # Step 3: Create and activate a virtual environment
      - name: Create virtual environment
        working-directory: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }} # Navigate to the backend directory
        run: |
          python -m venv venv
          source venv/bin/activate

      # Step 4: Install dependencies
      - name: Install dependencies
        working-directory: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
        run: |
          pip install -r requirements.txt --target=".python_packages/lib/site-packages"

      # Step 5: Zip backend for deployment
      - name: Create deployment package
        working-directory: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
        run: |
          zip -r ../release.zip . # Create the deployment artifact

      # Step 6: Upload deployment artifact for deploy job
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: azure-function-package
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    name: Deploy to Azure Function
    needs: build
    steps:
      # Step 1: Download the deployment package from the build job
      - name: Download deployment artifact
        uses: actions/download-artifact@v4
        with:
          name: azure-function-package

      # Step 2: Deploy to Azure Functions
      - name: Deploy to Azure Functions
        uses: Azure/functions-action@v1
        with:
          app-name: 'feedback-system-func' # Replace with your Azure Function App name
          slot-name: 'Production' # Replace with your deployment slot if applicable
          package: release.zip # Deployment artifact
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_D4CB348060A74F809BE825B7B338DBD6 }}
          sku: 'flexconsumption' # Ensure this matches your Azure Function's SKU
